/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        cream: "#FFF8F0",
        "warm-orange": "#FF6B35",
        "deep-green": "#1A3C34",
        "gold": "#FFD700",
        "soft-red": "#FF4757",
        "mint": "#E8FFF3",
        "card-bg": "#FFFFFF",
      },
      fontFamily: {
        display: ["Fredoka", "sans-serif"],
        body: ["Nunito", "sans-serif"],
      },
      keyframes: {
        "apple-fall": {
          "0%": { transform: "translateY(-60px) rotate(0deg)", opacity: "0" },
          "50%": { opacity: "1" },
          "100%": { transform: "translateY(0) rotate(15deg)", opacity: "1" },
        },
        "bounce-score": {
          "0%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.4)" },
          "100%": { transform: "scale(1)" },
        },
        "shake-card": {
          "0%, 100%": { transform: "translateX(0)" },
          "20%": { transform: "translateX(-8px)" },
          "40%": { transform: "translateX(8px)" },
          "60%": { transform: "translateX(-5px)" },
          "80%": { transform: "translateX(5px)" },
        },
        "pop-in": {
          "0%": { transform: "scale(0.5)", opacity: "0" },
          "70%": { transform: "scale(1.05)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "sparkle": {
          "0%": { transform: "scale(0) rotate(0deg)", opacity: "1" },
          "50%": { transform: "scale(1) rotate(180deg)", opacity: "1" },
          "100%": { transform: "scale(0) rotate(360deg)", opacity: "0" },
        },
        "confetti-fall": {
          "0%": { transform: "translateY(-10px) rotate(0deg)", opacity: "1" },
          "100%": { transform: "translateY(60px) rotate(360deg)", opacity: "0" },
        },
        "slide-up": {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "shake-hearts": {
          "0%, 100%": { transform: "translateX(0) rotate(0deg)" },
          "20%": { transform: "translateX(-6px) rotate(-5deg)" },
          "40%": { transform: "translateX(6px) rotate(5deg)" },
          "60%": { transform: "translateX(-4px) rotate(-3deg)" },
          "80%": { transform: "translateX(4px) rotate(3deg)" },
        },
        "bounce-streak": {
          "0%": { transform: "scale(1) translateY(0)" },
          "30%": { transform: "scale(1.2) translateY(-8px)" },
          "50%": { transform: "scale(0.95) translateY(2px)" },
          "70%": { transform: "scale(1.1) translateY(-4px)" },
          "100%": { transform: "scale(1) translateY(0)" },
        },
        "bounce-slow": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "shake-emoji": {
          "0%, 100%": { transform: "rotate(0deg)" },
          "20%": { transform: "rotate(-15deg)" },
          "40%": { transform: "rotate(15deg)" },
          "60%": { transform: "rotate(-10deg)" },
          "80%": { transform: "rotate(10deg)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "physicist-jump": {
          "0%": { transform: "translateY(200px) scale(0.3) rotate(-20deg)", opacity: "0" },
          "40%": { transform: "translateY(-30px) scale(1.1) rotate(10deg)", opacity: "1" },
          "60%": { transform: "translateY(10px) scale(0.95) rotate(-5deg)" },
          "80%": { transform: "translateY(-5px) scale(1.02) rotate(2deg)" },
          "100%": { transform: "translateY(0) scale(1) rotate(0deg)", opacity: "1" },
        },
        "physicist-idle": {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "25%": { transform: "translateY(-8px) rotate(-2deg)" },
          "50%": { transform: "translateY(-3px) rotate(0deg)" },
          "75%": { transform: "translateY(-10px) rotate(2deg)" },
        },
        "speech-bubble": {
          "0%": { transform: "scale(0) translateY(20px)", opacity: "0" },
          "50%": { transform: "scale(1.1) translateY(-5px)", opacity: "1" },
          "70%": { transform: "scale(0.95) translateY(3px)" },
          "100%": { transform: "scale(1) translateY(0)", opacity: "1" },
        },
        "shake-vigor": {
          "0%, 100%": { transform: "translateX(0) rotate(0deg) scale(1)" },
          "10%": { transform: "translateX(-8px) rotate(-8deg) scale(1.05)" },
          "20%": { transform: "translateX(8px) rotate(8deg) scale(1.05)" },
          "30%": { transform: "translateX(-6px) rotate(-6deg) scale(1.03)" },
          "40%": { transform: "translateX(6px) rotate(6deg) scale(1.03)" },
          "50%": { transform: "translateX(-4px) rotate(-4deg)" },
          "60%": { transform: "translateX(4px) rotate(4deg)" },
          "70%": { transform: "translateX(-2px) rotate(-2deg)" },
          "80%": { transform: "translateX(2px) rotate(2deg)" },
        },
        "fragment-pop": {
          "0%": { transform: "scale(0) rotate(-180deg)" },
          "50%": { transform: "scale(1.4) rotate(10deg)" },
          "70%": { transform: "scale(0.9) rotate(-5deg)" },
          "100%": { transform: "scale(1) rotate(0deg)" },
        },
        "fragment-ring": {
          "0%": { transform: "scale(1)", opacity: "0.8" },
          "100%": { transform: "scale(2.5)", opacity: "0" },
        },
        "rotate-wobble": {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
      },
      animation: {
        "apple-fall": "apple-fall 0.8s ease-out forwards",
        "bounce-score": "bounce-score 0.4s ease-out",
        "shake-card": "shake-card 0.5s ease-out",
        "pop-in": "pop-in 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards",
        "float": "float 3s ease-in-out infinite",
        "sparkle": "sparkle 0.6s ease-out forwards",
        "confetti-fall": "confetti-fall 1.2s ease-out forwards",
        "slide-up": "slide-up 0.5s ease-out forwards",
        "shake-hearts": "shake-hearts 0.5s ease-out",
        "bounce-streak": "bounce-streak 0.6s ease-out",
        "bounce-slow": "bounce-slow 2s ease-in-out infinite",
        "shake-emoji": "shake-emoji 0.5s ease-in-out",
        "fade-in": "fade-in 0.3s ease-out forwards",
        "physicist-jump": "physicist-jump 0.8s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "physicist-idle": "physicist-idle 2.5s ease-in-out infinite",
        "speech-bubble": "speech-bubble 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "shake-vigor": "shake-vigor 1s ease-in-out infinite",
        "fragment-pop": "fragment-pop 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "fragment-ring": "fragment-ring 0.8s ease-out forwards",
        "rotate-wobble": "rotate-wobble 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
